name:                rainbow-hash
version:             0.1.0.0
github:              "tmciver/rainbow-hash"
license:             BSD3
author:              "Tim McIver"
maintainer:          "tim@timmciver.com"
copyright:           "2018 Tim McIver"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/tmciver/rainbow-hash#readme>

dependencies:
- base >= 4.7 && < 5
- magic

library:
  source-dirs: src
  dependencies:
  - bytestring
  - directory
  - filepath
  - hashing
  - split
  - text

executables:
  rh-server:
    main:                Main.hs
    source-dirs:         server
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - rainbow-hash
    - directory
    - scotty
    - blaze-html
    - http-types
    - bytestring
    - wai-extra

  rh-cli:
    main:                Main.hs
    source-dirs:         cli
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - rainbow-hash
    - directory
    - filepath
    - bytestring

tests:
  rainbow-hash-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - rainbow-hash
